version: '3.7'

networks:
  todolist:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=grpc_todolist
      - MYSQL_USER=grpc_todolist
      - MYSQL_PASSWORD=grpc_todolist
      - TZ=Asia/Shanghai
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - todolist

  etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    container_name: etcd
    restart: on-failure
    privileged: true
    ports:
      - "2379:2379"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - ETCD_API=3
      - ETCD_CERT_FILE="/path/to/server.crt"
      - ETCD_KEY_FILE="/path/to/server.key"
      - ETCD_AUTH="simple"
      - ETCD_AUTH_USER="todolist"
      - ETCD_AUTH_PASSWORD="todolist"
    networks:
      - todolist


  etcd-keeper:
    image: "evildecay/etcdkeeper:latest"
    container_name: etcd-keeper
    environment:
      - ETCD_HOSTS = http://etcd:2379
      - SW_STORAGE_ETCD_CLUSTER_NODES = etcd:2379
      - HOST = 127.0.0.1
      - HOSTNAME = etcd-keeper
    links:
      - etcd
    ports:
      - "8080:8080"
    networks:
      - todolist
#
#  elasticsearch:
#    image: elasticsearch:8.4.2
#    container_name: elasticsearch
#    environment:
#      bootstrap.memory_lock: true
#      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
#      discovery.type: single-node
#      ingest.geoip.downloader.enabled: false
#      TZ: Asia/Shanghai
#      xpack.security.enabled: false
#    healthcheck:
#      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"] #⼼跳检测，成功之后不再执⾏后⾯的退出
#      interval: 60s #⼼跳检测间隔周期
#      timeout: 10s
#      retries: 3
#      start_period: 60s #⾸次检测延迟时间
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - /usr/local/elasticsearch/data:/usr/local/elasticsearch/data
#      - /usr/local/elasticsearch/config/es/config:/usr/local/elasticsearch/config
#    ports:
#      - "9200:9200"
#    restart: always
#    networks:
#      - todolist
#
#  skywalking-oap:
#    image: apache/skywalking-oap-server:9.3.0
#    container_name: skywalking-oap
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    links:
#      - elasticsearch
#    environment:
#      SW_HEALTH_CHECKER: default
#      SW_STORAGE: elasticsearch
#      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
#      JAVA_OPTS: "-Xms2048m -Xmx2048m"
#      TZ: Asia/Shanghai
#      SW_TELEMETRY: prometheus
#    healthcheck:
#      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s
#    restart: on-failure
#    ports:
#      - "11800:11800"
#      - "12800:12800"
#    networks:
#      - todolist
#
#  skywalking-ui:
#    image: apache/skywalking-ui:9.3.0
#    depends_on:
#      skywalking-oap:
#        condition: service_healthy
#    links:
#      - skywalking-oap
#    ports:
#      - "8080:8080"
#    environment:
#      SW_OAP_ADDRESS: http://skywalking-oap:12800
#      SW_HEALTH_CHECKER: default
#      TZ: Asia/Shanghai
#    healthcheck:
#      test: ["CMD-SHELL", "curl -sf http://localhost:8080 || exit 1"] #⼼跳检测，成功之后不再执⾏后⾯的退出
#      interval: 60s #⼼跳检测间隔周期
#      timeout: 10s
#      retries: 3
#      start_period: 60s #⾸次检测延迟时间
#    networks:
#      - todolist